import {
  PostBanksUserTransactionDTO as Transaction,
  BanksUserTransactionType as TransactionType,
  AccountType,
  BanksUserAccountWithTransactions,
} from '@algoan/rest';
import {
  AccountType as BiAccountType,
  Connection,
  Transaction as BiTransaction,
  TransactionType as BiTransactionType,
} from '../../interfaces/budget-insight.interface';
import {
  mapBudgetInsightAccount,
  mapBudgetInsightAccountsFromOneConnection,
  mapBudgetInsightTransactions,
} from './budget-insight.utils';

describe('BudgetInsightUtils', () => {
  const budgetInsightTransactions: BiTransaction[] = [
    {
      type: BiTransactionType.WITHDRAWAL,
      category: {
        name: 'category',
      },
      original_wording: 'original_wording',
      wording: 'wording',
      card: 'card',
      simplified_wording: 'simplifiedWording',
      value: 1,
      id_account: 9,
      id: 'id',
      rdate: '2010-01-15 15:55:00',
    },
  ];

  it('should map the budget insight connections to banksUser', () => {
    const budgetInsightConnections: Connection[] = [
      {
        active: true,
        last_update: '2010-01-15 15:53:00',
        bank: {
          name: 'bank-name',
        },
        accounts: [
          {
            type: BiAccountType.LOAN,
            balance: -10000,
            id: 9,
            name: 'account-name',
            currency: { id: 'USD' },
            iban: 'iban',
            last_update: '2009-01-15 15:53:00',
            bic: 'bic',
            loan: {
              type: BiAccountType.LOAN,
              rate: 1.1,
              next_payment_amount: 5,
              maturity_date: '2019-02-15 15:53:00',
              subscription_date: '1999-02-15 15:53:00',
              total_amount: 100000000,
              id_account: 'loan-account-id',
            },
          },
        ],
      },
      {
        active: true,
        last_update: '2010-01-15 15:53:00',
        bank: {
          name: 'bank-name',
        },
        accounts: [
          {
            type: BiAccountType.CARD,
            balance: 100,
            id: 9,
            name: 'account-name',
            currency: { id: 'USD' },
            iban: 'iban',
            last_update: '2009-01-15 15:53:00',
            bic: 'bic',
            loan: undefined,
          },
        ],
      },
    ];

    const expectedAccounts: BanksUserAccountWithTransactions[] = [
      {
        balance: -10000,
        balanceDate: 1232031180000,
        bank: 'bank-name',
        connectionSource: 'BUDGET_INSIGHT',
        currency: 'USD',
        bic: 'bic',
        iban: 'iban',
        loanDetails: {
          amount: 100000000,
          debitedAccountId: 'loan-account-id',
          endDate: 1550242380000,
          interestRate: 1.1,
          payment: 5,
          remainingCapital: -10000,
          startDate: 919090380000,
          type: 'LOAN',
        },
        name: 'account-name',
        reference: '9',
        savingsDetails: 'loan',
        status: 'ACTIVE',
        transactions: [
          {
            id: 'id1',
            amount: 1,
            banksUserCardId: 'card',
            category: 'category',
            date: '2010-01-15T14:55:00.000Z',
            description: 'original_wording',
            reference: 'id',
            simplifiedDescription: 'simplifiedWording',
            type: TransactionType.ATM,
            userDescription: 'wording',
          },
        ],
        type: AccountType.LOAN,
        usage: 'PERSONAL',
      },
      {
        balance: 100,
        balanceDate: 1232031180000,
        bank: 'bank-name',
        connectionSource: 'BUDGET_INSIGHT',
        currency: 'USD',
        bic: 'bic',
        iban: 'iban',
        loanDetails: undefined,
        name: 'account-name',
        reference: '9',
        savingsDetails: 'card',
        status: 'ACTIVE',
        transactions: [
          {
            id: 'id2',
            amount: 1,
            banksUserCardId: 'card',
            category: 'category',
            date: '2010-01-15T14:55:00.000Z',
            description: 'original_wording',
            reference: 'id',
            simplifiedDescription: 'simplifiedWording',
            type: TransactionType.ATM,
            userDescription: 'wording',
          },
        ],
        type: AccountType.CREDIT_CARD,
        usage: 'PERSONAL',
      },
    ];

    expect(mapBudgetInsightAccount(budgetInsightConnections, budgetInsightTransactions)).toEqual(expectedAccounts);
  });

  it('should map the budget insight transactions to banksUser', () => {
    const expectedAccounts: Transaction[] = [
      {
        amount: 1,
        banksUserCardId: 'card',
        category: 'category',
        date: '2010-01-15T14:55:00.000Z',
        description: 'original_wording',
        reference: 'id',
        simplifiedDescription: 'simplifiedWording',
        type: TransactionType.ATM,
        userDescription: 'wording',
      },
    ];

    expect(mapBudgetInsightTransactions(budgetInsightTransactions)).toEqual(expectedAccounts);
  });
  it('should map the budget insight connection to banksUser', () => {
    const event: { connection: Connection } = ({
      user: {
        signin: '2019-11-25 17:36:55',
        platform: 'sharedAccess',
        id: 1,
      },
      connection: {
        bank: {
          name: 'This name',
        },
        connector_uuid: '338178e6-3d01-564f-9a7b-52ca442459bf',
        id_user: 1,
        created: '2020-01-23 18:38:43',
        id_provider: 59,
        error_message: undefined,
        last_push: undefined,
        last_update: '2020-05-18 10:36:50',
        connector: {
          sync_frequency: undefined,
          code: undefined,
          color: '5c2963',
          auth_mechanism: 'credentials',
          id: 59,
          uuid: '338178e6-3d01-564f-9a7b-52ca442459bf',
          account_types: ['perco', 'checking', 'loan', 'savings', 'card', 'pee', 'market', 'lifeinsurance'],
          documents_type: [],
          restricted: false,
          available_transfer_mechanisms: ['credentials'],
          capabilities: [
            'profile',
            'banktransfer',
            'banktransferaddrecipient',
            'contact',
            'bankwealth',
            'document',
            'bank',
          ],
          transfer_beneficiary_types: ['recipient'],
          transfer_execution_date_types: ['first_open_day', 'deferred'],
          months_to_fetch: undefined,
          siret: undefined,
          hidden: false,
          beta: false,
          slug: 'EXA',
          categories: [],
          name: 'Connecteur de test',
          available_auth_mechanisms: ['credentials', 'webauth'],
          urls: [],
          charged: false,
        },
        active: true,
        state: undefined,
        expire: undefined,
        accounts: [
          {
            ownership: 'owner',
            loan: undefined,
            webid: '3002900000',
            // eslint-disable-next-line id-blacklist
            number: '3002900000',
            disabled: undefined,
            currency: {
              name: 'Euro',
              symbol: '€',
              crypto: false,
              precision: 2,
              prefix: false,
              marketcap: undefined,
              datetime: undefined,
              id: 'EUR',
            },
            id: 274,
            bookmarked: 0,
            formatted_balance: '2381,86 {',
            id_connection: 76,
            original_name: 'Compte chèque',
            last_update: '2020-05-18 10:36:40',
            id_source: 133,
            company_name: undefined,
            usage: 'PRIV',
            type: 'checking',
            recipients: [],
            information: {},
            deleted: undefined,
            id_parent: undefined,
            bic: 'CDTBFRBIXXX',
            iban: 'EX6713679564637300290000028',
            id_type: 2,
            coming_balance: 2381.86,
            coming: undefined,
            transfers: [],
            id_user: 1,
            name: 'Compte chèque',
            display: true,
            transactions: [
              {
                comment: undefined,
                informations: {
                  weboob: 'yes',
                },
                webid: undefined,
                active: true,
                simplified_wording: 'DEBIT MENSUEL CARTE',
                original_gross_value: undefined,
                id: 6394,
                original_value: undefined,
                original_wording: 'DEBIT MENSUEL CARTE',
                id_account: 274,
                id_cluster: undefined,
                deleted: undefined,
                last_update: '2020-05-18 10:36:41',
                commission: undefined,
                state: 'fail_categorizing',
                gross_value: undefined,
                new: true,
                type: 'summary_card',
                commission_currency: undefined,
                id_category: 9998,
                counterparty: undefined,
                original_currency: undefined,
                nopurge: 0,
                formatted_value: '-837,95 €',
                rdate: '2020-01-31',
                coming: false,
                date: '2020-01-31',
                application_date: '2020-01-31',
                card: undefined,
                date_scraped: '2020-02-01 17:24:05',
                bdate: '2020-01-31',
                vdate: undefined,
                country: undefined,
                value: -837.95,
                documents_count: 0,
                stemmed_wording: 'DEBIT MENSUEL CARTE',
                wording: 'DEBIT MENSUEL CARTE',
              },
            ],
            error: undefined,
            balance: 2381.86,
          },
        ],
        error: undefined,
        id_bank: 59,
        next_try: '2020-05-19 13:06:50',
        id_connector: 59,
        id: 76,
      },
      push_type: 'partial_history',
    } as unknown) as { connection: Connection };

    const expectedAccounts: BanksUserAccountWithTransactions[] = ([
      {
        balance: 2381.86,
        balanceDate: 1589791000000,
        bank: 'This name',
        bic: 'CDTBFRBIXXX',
        connectionSource: 'BUDGET_INSIGHT',
        currency: 'EUR',
        iban: 'EX6713679564637300290000028',
        loanDetails: undefined,
        name: 'Compte chèque',
        reference: '274',
        savingsDetails: 'checking',
        status: 'ACTIVE',
        transactions: [
          {
            amount: -837.95,
            banksUserCardId: undefined,
            category: undefined,
            date: '2020-01-30T23:00:00.000Z',
            description: 'DEBIT MENSUEL CARTE',
            reference: '6394',
            simplifiedDescription: 'DEBIT MENSUEL CARTE',
            type: 'OTHER',
            userDescription: 'DEBIT MENSUEL CARTE',
          },
        ],
        type: 'CHECKINGS',
        usage: 'PERSONAL',
      },
    ] as unknown) as BanksUserAccountWithTransactions[];

    expect(mapBudgetInsightAccountsFromOneConnection(event.connection)).toEqual(expectedAccounts);
  });
});
